# Site settings
title: Gene's Adventures in Web Development
header-img: img/home-bg.png
email: geneedwinm@gmail.com
copyright_name: FamousWiz
description: > # this means to ignore newlines until "baseurl:"
  Follow me as I find my place in the world of coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  FamousWiz
learn_profile: FamousWiz
email_username: geneedwinm@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
